### ISSUE TITLE
Is this project Dead?

### ISSUE THREAD

**Issue by chrisjowen** [justuseapen/virtuoso#49]
Just saw a talk by @justuseapen and I felt the this was a well thought out framework, though when I looked the repo I see that the last commit was 5 months ago, just wondering if this is still an active project?

**Comment by chrisjowen** [comment]
Seems so :/

**Comment by justuseapen** [comment]
Ah yes I haven't really worked on it in a while! I'm sorry. Happy to answer questions like this though.
